### ISSUE TITLE
502 Bad Gateway after PG&E Auth

### ISSUE THREAD

**Issue by ChrisRomp** [JPHutchins/open-energy-view#28]
After authorizing PG&E I'm redirected back to `https://www.openenergyview.com/api/utility/pge/redirect_uri?...` but nginx shows a 502 Bad Gateway error.

**Comment by JPHutchins** [comment]
Hello!  Really glad that you tried it out but unfortunately the PGE auth has been down for a few months while I relocated the server.  I can update this thread when I update my creds with PGE.

**Comment by ChrisRomp** [comment]
No worries, it looks like great work!  I'll keep an eye out for an update.  I have an Eagle 200 that reads from my meter which gets me some data, but I like your aggregation.

Unrelated question: Does the PG&E API also include current rate $/kWh info for the subscriber?

**Comment by JPHutchins** [comment]
@ChrisRomp Hello, I have updated the servers and tested OAuth again this morning and it seems "OK".  I'm sure there are tons of bugs but I'd love to close this issue if you have a chance to go through the OAuth again.  Thanks!

re: $ rate, yes, it is possible but the implementation on my side is not done.  During OAauth PGE asks if you want to share "billing info".  It includes tiering and all that!

**Comment by ChrisRomp** [comment]
@JPHutchins Auth seems to be working now. 👍🏻 Which scopes does this need access to? Would love to give it only the scopes it needs. Didn't see it in the docs but didn't look for very long.

**Comment by ChrisRomp** [comment]
Scopes:
![image](https://user-images.githubusercontent.com/1683889/147606408-4cf12cb3-7676-4ef8-859c-6e25596a1a35.png)

**Comment by JPHutchins** [comment]
@ChrisRomp Basic Information and Usage Information are required IIRC.  Billing Information provides access to the rates that you mentioned but it's not implemented.

My guess is that unchecking Billing Information will be OK but unchecking the other two will give me unhandled errors in my logs lol!

**Comment by ChrisRomp** [comment]
Well that might explain why my data isn't loading. I'll give it another go with all three.

**Comment by JPHutchins** [comment]
"Might" - I will check what I pulled into the DB for your account and get back to you.

**Comment by ChrisRomp** [comment]
I went ahead and reauthed it just now anyway.  Also this only pulls in electric, not gas, correct?

**Comment by ChrisRomp** [comment]
Does this pull in historical data, or just moving forward? Second auth with all three scopes selected, and I'm not seeing data. I can check back later.

**Comment by JPHutchins** [comment]
It should pull historical but I don't think it's working.  I will tag you when I see data populated in your account.

**Comment by JPHutchins** [comment]
@ChrisRomp It may bring in some data if you refresh - I manually requested it.  As always I am hesitant to blame PGE for anything, but it seems like the http resource that it is making available is not available "when I receive it" but rather "at some point in the near future".

**Comment by ChrisRomp** [comment]
Seeing some data now.

**Comment by JPHutchins** [comment]
Cool!  When you had registered earlier I had forgotten to start the celery workers.  If you reregister again it may correctly initiate the pulling of the 4-year energy usage history.

**Comment by JPHutchins** [comment]
@ChrisRomp I identified a bug in which reregistering with the same nickname for the service would cause the registration to fail silently (hang on frontend).  I hope that a fix I put in resolves this error.

**Comment by ChrisRomp** [comment]
Nice! Anything I can do to help test?

**Comment by JPHutchins** [comment]
Go ahead and reregister and hopefully it pulls in the entire history.  I
won’t follow up tonight but I can check logs again tomorrow to see how it
goes.

**Comment by ChrisRomp** [comment]
I've reinitialized.  One thing that's odd is I can't see past (from today, Dec 29) Dec 27. Why wouldn't data from yesterday, Dec 28, be in there?

**Comment by JPHutchins** [comment]
The data from PGE lags by about 1.5 days and should update once every 24
hours.  The target history duration is 4 years (complicated if
addresses/accounts have changed), how long does your data go back?

**Comment by ChrisRomp** [comment]
Dec 1, 2021, it seems.

**Comment by ChrisRomp** [comment]
At least the data jives with what I'm seeing in Home Assistant via my Eagle 200 smart meter connection.

![image](https://user-images.githubusercontent.com/1683889/147687846-02920a32-358a-4e72-8778-680375f620a8.png)

**Comment by JPHutchins** [comment]
Longshot, but IIRC the frontend refreshes once it has acquired "one month" of data and then continues fetching the rest of the history in the background (takes 1-2 minutes).  Perhaps refreshing the page will reveal more history?

**Comment by ChrisRomp** [comment]
Yes - back to July 2019 now.

**Comment by JPHutchins** [comment]
Wooo!  I am terrible at UI and even if it was well designed it probably wouldn't work lol

**Comment by JPHutchins** [comment]
Now that you have the history, here's my pitch:

Given that HA has a history of devices turning on and off, and OEV has the energy history, the idea is for some Smart People™ to do the math that estimates the energy usage for each HA component and then uses those estimates to provide real time energy usage in HA.

**Comment by ChrisRomp** [comment]
I'm terrible at math. ;)  But HA isn't really the weak link in my setup; some of my monitoring equipment that feeds HA will drop out once in a while, though. The Eagle 200 sometimes needs to be reset (uses PoE so easy enough to automate). I also have Emporia monitors on my panels (main and 1 sub) and it's fairly decent but sometimes I think the wifi craps out.  On individual plugs I have a ton of Sonoff S31 devices (which have energy monitoring) running Tasmota, and those have been super solid except I had one device fail out of 15 or so.  But after a while I have to wonder how much all my energy monitoring is contributing to my energy use! 😅

**Comment by JPHutchins** [comment]
I've had the same thought - I'd suppose that it's the WiFi radios not the Hall effect sensors or MCUs that are using the most power.  Still, assuming that the data is used to optimize the use of power hungry devices, the small passive consumption budget is well worth it.

Putting current sensors on every circuit at the panel seems smart and a few companies make these though they are geared towards industrial use.

Further, an installation like yours has "real data" that could help to train the models that estimate power consumption based on total usage + on/off cycles.

**Comment by jordancurve** [comment]
I’m seeing the “502 Bad Gateway” error when trying to connect Enertalk to my PG&E account.
