### ISSUE TITLE
Website appears to be down

### ISSUE THREAD

**Issue by Weldawadyathink** [JPHutchins/open-energy-view#29]
Beta website appears to be down right now.

**Comment by JPHutchins** [comment]
@Weldawadyathink Thank you for letting me know!  It's back up right now but will only support the "Try the demo account" - I will be working over the next couple of weeks to get registration for PGE customers working again.  I will post updates to this thread as I have info: https://community.home-assistant.io/t/pg-e-energy-monitoring-integration/336038/14
