### ISSUE TITLE
Dashboard Date defaults to December 31, 1969

### ISSUE THREAD

**Issue by michaellunzer** [JPHutchins/open-energy-view#34]
Thanks for inviting me to try out Open Energy View!

**Steps I've taken:**
I've signed up using my Google account. After, I connected it to my PG&E Account.

**Issue**:
I saw that the graphs and charts weren't populated and thought it would take a some time for the data to populate. I checked a few days later and the graphs were still blank. I realized that the dates were for the year 1969 (I wasn't a customer at that point in time lol)

![image](https://user-images.githubusercontent.com/10967175/148157692-a71bb36a-6dd0-4322-b79f-4054188da226.png)

Additionally, when I go to change the date range, I only can select the year 1969:

![image](https://user-images.githubusercontent.com/10967175/148158026-b4a394c6-5d73-4fb3-9569-304ea0c176f4.png)

Any thoughts?

**Comment by JPHutchins** [comment]
Hi @michaellunzer, thank you for testing!  I can see that your data was pulled from the PGE servers but unfortunately it is of the 900 second interval variety that the frontend does not yet support.  It is my top priority to support this since more and more meters are using it, including my own!

**Comment by JPHutchins** [comment]
Continue here: https://github.com/JPHutchins/open-energy-view/issues/30

**Comment by michaellunzer** [comment]
thanks for explaining that! I'll follow the other issue #30
