### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by ChrisMD123** [JPHutchins/open-energy-view#37]
After going through the PG&E authorization process without error, I am receiving a 502 bad gateway error and cannot proceed any further on Open Energy View. If I go back to my PG&E authorizations page, I do not see Open Energy View on the list.

**Comment by JPHutchins** [comment]
@ChrisMD123 Thank you for testing!  The registration with PGE is currently down but should be up by the end of the week.  I'll tag you in this issue when it's ready to test again.

**Comment by JPHutchins** [comment]
@ChrisMD123 A user has reported that registration worked for them, give it a shot when you're able.  Thanks again!

**Comment by ChrisMD123** [comment]
It worked! Closing the issue. However, it only picked up one account out of two (electric but not gas), and only data through October 2021 are visible. Should I open a new issue for that?

**Comment by JPHutchins** [comment]
@ChrisMD123  Gas is not supported by OEV yet, you can track progress here: https://github.com/JPHutchins/open-energy-view/issues/32

You should open a ticket for the other issue if:
* the PGE account at that address is older than Oct 2021 (it can't deal with changing addresses)
* you have logged out of OEV and back in (or just refreshed the page)

It would be good to track - it might be something I have to pursue with PGE as it reminds me of a previous sighting I had!
