### ISSUE TITLE
PG&E electricity view stops abruptly after October 12, 2021

### ISSUE THREAD

**Issue by ChrisMD123** [JPHutchins/open-energy-view#38]
While I was successful in getting past the #37 issue, electrical data only updated through October 12, 2021. No data past that date are shown despite no changes on the utility service side.

**Comment by JPHutchins** [comment]
There are two things that can cause this: PG&E switched your reporting to the 900 second intervals or they "internally changed your account number and sometimes there is a bug" - another thing I'd need to look into.

**Comment by JPHutchins** [comment]
@ChrisMD123 Can you try again when you have a chance?  The fetches should support 15 minute intervals now.

**Comment by ChrisMD123** [comment]
It's working now, although there are some data gaps:
![image](https://user-images.githubusercontent.com/4922831/193356952-b328ae85-05bb-4814-bf46-ed6c2495c265.png)

**Comment by JPHutchins** [comment]
I'd suppose those are time periods where my server was offline ☹️ .  I've needed to add a button or automation that periodically checks for gaps, so I'll open a new issue.
