### ISSUE TITLE
Stuck on spinning circle after naming meters

### ISSUE THREAD

**Issue by jimmyli56** [JPHutchins/open-energy-view#46]
Not sure if it's because my account with PGE is new, but I am unable to link my accounts and met with a spinning circle after the step you name your gas and electric meters.

**Comment by JPHutchins** [comment]
I am able to recreate this - the `api/web/add/pge_oauth` endpoint is returning 502.

**Comment by JPHutchins** [comment]
I think that the PGE API may have changed so I will work on correcting this.

**Comment by JPHutchins** [comment]
This call is not returning expected XML, here is the unexpected response:
```xml
<ns1:feed xmlns:ns1="http://www.w3.org/2005/Atom">
    <ns1:id>977a5a2b-a9a7-41fb-a324-6c16c1c3e2a7</ns1:id>
    <ns1:title type="text">Green Button Usage Feed</ns1:title>
    <ns1:updated>2022-05-19T04:37:06.959Z</ns1:updated>
    <ns1:link href="https://api.pge.com/GreenButtonConnect/espi/1_1/resource/Subscription/7524008/UsagePoint/4365551713/MeterReading" rel="self"/>
</ns1:feed>
```

**Comment by jimmyli56** [comment]
That is indeed strange, I definitly think the API must've been updated since It looked like it was working fine with others before.

**Comment by JPHutchins** [comment]
@jimmyli56 Hey, I just tried registering again and it worked.  Maybe give it a try when you have a chance!

I am guessing that PGE's servers were not working correctly when you were trying before.  Sometimes their servers are down/weird (planned or not) which is something that OEV should handle better.

Thanks!

**Comment by jimmyli56** [comment]
Hmm, that's strange then, I still met with the spinning circle after naming the meters.

**Comment by JPHutchins** [comment]
@jimmyli56 Hello, could you try this again when you have a chance?   Thanks!

**Comment by jimmyli56** [comment]
@JPHutchins looks like it works nicely now, going to close this issue now.
