### ISSUE TITLE
Website shows date of Dec 31, 1969 (still)

### ISSUE THREAD

**Issue by pdawg17** [JPHutchins/open-energy-view#48]
Is this issue supposed to be resolved? I just registered and it shows a date of Dec 31, 1969.

**Comment by JPHutchins** [comment]
No, this is likely because your data is in 15 minute intervals instead of 60 minute intervals.  You can track it here: https://github.com/JPHutchins/open-energy-view/issues/30

**Comment by JPHutchins** [comment]
@pdawg17 Hi, could you try again when you have a chance?

**Comment by pdawg17** [comment]
> @pdawg17 Hi, could you try again when you have a chance?

Looks good now, thanks!

**Comment by JPHutchins** [comment]
Cool!  It was silly of me to invite people today since I am reorganizing my
network closet, it should be up again in under an hour.
